### ISSUE TITLE
无边框窗口登录页面无法点击按钮

### ISSUE THREAD

**Issue by Sam0523** [kooritea/electronic-wechat#1]
启动后显示之前登录的帐号，但要求在手机确认登录的时候，点击整个窗口的任何地方都会变成拖动窗口，而无法点击登录或切换帐号按钮。

DE: GNOME 3.28

**Comment by kooritea** [comment]
切换账号按钮无法点击的问题已经在之前的提交修复好了，修复之后的版本马上就会发布～
