### ISSUE TITLE
消息无法收到或同步？

### ISSUE THREAD

**Issue by WuWeiWW** [kooritea/electronic-wechat#10]
不知道为什么用这版本，经常收不到消息，手机发出的也没有同步
我换成 `geeeeeeeeek/electronic-wechat` 就没问题
是有改过什么吗

**Comment by vic-feng** [comment]
你说的那个分支我一直在Ubuntu 16.04.4 LTS上使用，没有这种情况的。
现在的这个分支我也遇到了同样的情况，就是https://github.com/kooritea/electronic-wechat/issues/9

**Comment by kooritea** [comment]
重要重要！！
消息丢失是我的郭！！
现在已经紧急发布[2.0.9](https://github.com/kooritea/electronic-wechat/releases/tag/v2.0.9)！！
