### ISSUE TITLE
汉化不完全

### ISSUE THREAD

**Issue by std4453** [kooritea/electronic-wechat#11]
在英语版系统中，通过preference切换到中文界面，发现很多文字没有得到汉化，如：
搜索框中仍然显示的是Search，弹出菜单中如New Chat, Log out等仍然是英语。
环境：Ubuntu 18.04
截图：
![screenshot from 2018-05-27 13-25-35](https://user-images.githubusercontent.com/13191718/40582801-a47cdbe6-61b2-11e8-95b8-004a8a8cf920.png)
![screenshot from 2018-05-27 13-34-35](https://user-images.githubusercontent.com/13191718/40582805-bc6a4efa-61b2-11e8-835c-8607bd5d8531.png)
设置：
![screenshot from 2018-05-27 13-35-20](https://user-images.githubusercontent.com/13191718/40582810-d56793e0-61b2-11e8-9670-2da785c9efd7.png)

**Comment by kooritea** [comment]
的确有这个问题，中文系统也无法切换到英文界面了

**Comment by kooritea** [comment]
找到问题原因是在扫码登录到进入主界面之间url丢失了一个lang的参数
还没想到解决方法。。
