### ISSUE TITLE
网络代理问题

### ISSUE THREAD

**Issue by vic-feng** [kooritea/electronic-wechat#13]
#### Description

由于系统本身设置代理的时候，只有‘自动’、‘手动’、‘禁用’三个选项，当选择手动的时候，会影响到electronic-wechat使用，带来无法正常登录、二维码无法正常获取等问题。可否考虑对electronic-wechat增加一设置选项，用来选择‘使用系统代理’或者‘不使用系统系代理’

#### Specifications

- Version of Electron (run `$ electron --version`): `v2.0.0`
- OS: `Ubuntu 18.04 LTS`
- Kernel Version: `4.15.0-22-generic`

**Comment by kooritea** [comment]
应该不能越过系统代理吧
除非root
electron上也没找到相关的说明

**Comment by vic-feng** [comment]
@kooritea 
若有机会了，加入此功能，感激～
