### ISSUE TITLE
托盘右键菜单巨大

### ISSUE THREAD

**Issue by amitbha** [kooritea/electronic-wechat#14]
#### Specifications

- Version of electronic-wechat (2.0.9)
- OS: `Manjaro Linux 17.1.10`
- Gnome shell 3.28.2

#### Problem

托盘图标的右键菜单非常巨大，怀疑是图标尺寸导致的。如图
![2018-05-31 09-33-47](https://user-images.githubusercontent.com/4060625/40756616-1903a2e0-64b7-11e8-83a0-7f1232cdb258.png)

**Comment by kooritea** [comment]
。。。。
有试过更换gnome shell的主题吗

**Comment by amitbha** [comment]
换回默认主题，依然如此。
是不是少装了和主题有关的依赖？

**Comment by kooritea** [comment]
emmm
我也没有特别安装过什么依赖
不过原图图标尺寸确实是比较大
到时候我做一套标准icon尺寸的图标再试试吧。。

**Comment by liangjiongyao** [comment]
我在CenOS7.5上也是这样的情况
