### ISSUE TITLE
右键复制消息无效

### ISSUE THREAD

**Issue by amitbha** [kooritea/electronic-wechat#15]
#### Description

右键点击消息，选择“复制”，没有任何效果，无法粘贴。
> 其实这个问题，被fork前就存在了。

**希望的效果是**：至少支持文字消息的复制，如果里面的表情也支持就更好了。

#### Specifications

- Version of Electron-wechat: `v2.0.9`
- OS: `manjaro linux 17.1.10`

**Comment by kooritea** [comment]
是的，现在还不知道原来是用什么方法进行复制的，
打算clipboard用代替
可是我还不会angular，暂时没办法解决

**Comment by sansroman** [comment]
通过indexDB注入的数据没有绑定上菜单事件，其他情况测试正常

**Comment by kooritea** [comment]
@sansroman 已经在已知bug里面 解决方法未知：）

**Comment by sansroman** [comment]
我复制功能是正常的  只是历史信息没有右键菜单 难道是系统的问题么，我是archlinux 4.17.14

**Comment by kooritea** [comment]
复制功能是我修复了，只是仅限纯文本消息有效，历史消息没有右键是因为暴力注入，解决方法未知
