### ISSUE TITLE
您能不能把snap版的electronic-wechat也更新下？！

### ISSUE THREAD

**Issue by dkgdsc** [kooritea/electronic-wechat#18]
我今天下了snap版的electronic-wechat，点击运行，登入界面浮现不出。看了下，snap版的electronic-wechat估计是2.0版。希望您能不能更新下snap版的electronic-wechat。虽然可能只有几个人在用，但我觉得只有有人在用就应该维护更新。不知道snap版的electronic-wechat是谁开发维护的，可能那个人不维护更新了！我希望您能不能维护更新下？可以的话！

**Comment by kooritea** [comment]
因为之前的版本不是我上传的更新肯定是不行了
等我有空的时候再学一下怎样打包成snap吧。。

**Comment by dkgdsc** [comment]
谢谢您的回复！但愿能早日看到那一天

**Comment by Jinva** [comment]
+1
