### ISSUE TITLE
出来一个这个“下载微信PC版”提示

### ISSUE THREAD

**Issue by left3721** [kooritea/electronic-wechat#20]
![image](https://user-images.githubusercontent.com/21092101/40950815-e0fa2326-68a6-11e8-8937-239861127783.png)

系统是ubuntu 18.04
微信版本V2.0.9

**Comment by vic-feng** [comment]
@left3721 @kooritea 
我也出现了同样的问题，正准备提交问题了，发现已经有人提交了
顺便想问一下，图片是怎么插入的？

**Comment by amitbha** [comment]
同样的问题，是不是封号的前奏？
我已经登录不上了

**Comment by amitbha** [comment]
@vic-feng 就在输入框底下，Attach files

**Comment by left3721** [comment]
@vic-feng 我是用shutter抓图，直接复制粘贴就可以

**Comment by kooritea** [comment]
tx真是不给linux活路呀
暂时用css隐藏了这个东西
