### ISSUE TITLE
多实例取消了吗？

### ISSUE THREAD

**Issue by liangjiongyao** [kooritea/electronic-wechat#21]
我点击dash to dock上的微信图标或者左上角application里面的微信图标仍然会启动另外一个新的实例。
![1](https://user-images.githubusercontent.com/30697104/41146856-59de5efa-6b37-11e8-82a6-bbdf8f7d6c1f.png)
![2](https://user-images.githubusercontent.com/30697104/41147049-e527ae94-6b37-11e8-8c8d-dc834919a3fa.png)
![3](https://user-images.githubusercontent.com/30697104/41147343-be69a342-6b38-11e8-8816-2a3a12450415.jpg)

**Comment by kooritea** [comment]
取消了多实例的检查，也就是说不管存不存在已经打开的实例，点击没有缩小到dock时都会新建一个实例
如果想要点击dock来显示之前的实例，可以按左上角第三个按钮让微信缩小到dock

**Comment by liangjiongyao** [comment]
你说的左上角第三个按钮是哪个？我没找到，额。

**Comment by kooritea** [comment]
就是窗口顶部那三个按钮你的在右上角，你开了无边框就在左上角了

**Comment by liangjiongyao** [comment]
thx
