### ISSUE TITLE
Kali Linux 2018.2 无法显示electronic-wechat状态栏图标

### ISSUE THREAD

**Issue by vic-feng** [kooritea/electronic-wechat#22]
#### Description

你好，今天在Kali Linux 2018.2 系统上使用electronic-wechat，有个问题就是无法在状态栏显示图标，这样一来就无法进行偏好设置了。

#### Specifications

- Version of Electron (run `$ electron --version`): `v2.0.0`
- OS: `Kali Linux 2018.2`
- Kernel: `4.16.0-kali2-amd64`

**Comment by kooritea** [comment]
用 ALT 可以唤出菜单栏

**Comment by vic-feng** [comment]
一开始可以，但是现在不知什么原因唤不出来了

**Comment by kooritea** [comment]
使用shift+ctrl+i调出控制台，有什么错误日志吗

**Comment by vic-feng** [comment]
vendor_01049f2.js:18 Mixed Content: The page at 'https://wx.qq.com/' was loaded over HTTPS, but requested an insecure image 'http://mmbiz.qpic.cn/mmbiz_jpg/yNKv1P4Q9eUKB8Y0jUXQXesBOh2OeyEtESRH68tQu4zk9jUMkQwwN4VZDib3PVC6CcibInUHGESmAFibtLqahoPkA/300?wxtype=jpeg&wxfrom=0'. This content should also be served over HTTPS.
(anonymous) @ vendor_01049f2.js:18
vendor_01049f2.js:18 Mixed Content: The page at 'https://wx.qq.com/' was loaded over HTTPS, but requested an insecure image 'http://mmbiz.qpic.cn/mmbiz_jpg/yNKv1P4Q9eUKB8Y0jUXQXesBOh2OeyEtnyRQMLIGXDLTwU3nibjha1MneGKWp28tXchib4opkREGLtbblJ86EWIA/640?wxtype=jpeg&wxfrom=0'. This content should also be served over HTTPS.
(anonymous) @ vendor_01049f2.js:18
vendor_01049f2.js:18 Mixed Content: The page at 'https://wx.qq.com/' was loaded over HTTPS, but requested an insecure image 'http://mmbiz.qpic.cn/mmbiz_jpg/1EUW9uUoIX6VtVaibnKiaOhkIbU8ZGiaPssj94dRtxv4eGlFPN6S0pjUFaorgWXYiahSBbNdluiaCjf3F1cqHEZ625g/640?wxtype=jpeg&wxfrom=0'. This content should also be served over HTTPS.
(anonymous) @ vendor_01049f2.js:18
vendor_01049f2.js:18 Mixed Content: The page at 'https://wx.qq.com/' was loaded over HTTPS, but requested an insecure image 'http://mmbiz.qpic.cn/mmbiz_jpg/Z6bicxIx5naKicVMR3Czo4o9uia0QkRuPuCicKcLeXljwd2fnHK7g8ffAxoPZsbpexNgKDUxTiaMFm8Qcm8icGGyYbaw/640?wxtype=jpeg&wxfrom=0'. This content should also be served over HTTPS.
(anonymous) @ vendor_01049f2.js:18
vendor_01049f2.js:18 Mixed Content: The page at 'https://wx.qq.com/' was loaded over HTTPS, but requested an insecure image 'http://mmbiz.qpic.cn/mmbiz_jpg/sGfPWsuKAfc6Lr9QvJ4GpIjYrueDd8XiaqWNOIFIhYVyUbdDBEibUKsopb2gD4rh2Rm3mUazrvpK1LKQnRMgzHBg/640?wxtype=jpeg&wxfrom=0'. This content should also be served over HTTPS.
(anonymous) @ vendor_01049f2.js:18
vendor_01049f2.js:18 Mixed Content: The page at 'https://wx.qq.com/' was loaded over HTTPS, but requested an insecure image 'http://mmbiz.qpic.cn/mmbiz_jpg/NkE3uMFiafXHvrtia7hfW51TIeQ96tbAn1YXItz87ZVlZ6YfzcgCbDbqS5wkEB3VA5g1Xia3cf4Gdvv7drx7V1AMQ/300?wxtype=jpeg&wxfrom=0'. This content should also be served over HTTPS.
(anonymous) @ vendor_01049f2.js:18
vendor_01049f2.js:18 Mixed Content: The page at 'https://wx.qq.com/' was loaded over HTTPS, but requested an insecure image 'http://mmbiz.qpic.cn/mmbiz_jpg/rFWVXwibLGtwRWSuuiaUxpkIeUwx2zmm7diaxp9VCHWRrK7vHYic4qhnwpIGLWzdxa1km9Qe4GyIwxQHO1xtHrY4Nw/640?wxtype=jpeg&wxfrom=0'. This content should also be served over HTTPS.

**Comment by kooritea** [comment]
emm 这些都没有问题
托盘图标问题可以参考(#8 )
我想不出来为什么不能唤出菜单栏,除非你用了无边框模式(无边框模式是不能唤出菜单栏的)

**Comment by vic-feng** [comment]
我犯了低级错误，的确是无边框模式
