### ISSUE TITLE
请问您能不能在打包的时候打包一个icon文件进去呢？

### ISSUE THREAD

**Issue by windghoul** [kooritea/electronic-wechat#23]
在ubuntu下做快捷方式，有一个icon的图标会好看一点，能不能在打包的时候上传一个，如果涉及到版权的问题就算了。谢谢您

**Comment by liangjiongyao** [comment]
你可以自己做个图标，百度一下千库网，进去搜微ixn图标，可漂亮了

**Comment by windghoul** [comment]
@liangjiongyao 不是呀，因为打包进去之后就不需要把icon图标放在外面可以固定路径就好做快捷方式了，要不然每次更新之后都要该图片的路径或者把图片放到路径里面

**Comment by kooritea** [comment]
这里可以下载图标https://github.com/kooritea/electronic-wechat/blob/master/assets/icon.png
下个版本我会把图标放在assets/icon.png

**Comment by windghoul** [comment]
@kooritea 谢谢～
