### ISSUE TITLE
只想为作者推出的代理选择功能点个大赞！

### ISSUE THREAD

**Issue by vic-feng** [kooritea/electronic-wechat#25]
早上来上班，收到了更新通知发现增加了代理设置功能，很开心！
现在系统默认情况下开启了全局代理模式，只需要把不需要用到国际网络的软件一律设置为不使用系统代理就方便很多了！
感谢作者的成果，为electronic-wechat增加了代理选择功能
![2018-06-19 10-02-06](https://user-images.githubusercontent.com/34942652/41571935-1310ed0c-73a8-11e8-8ffd-931dc7312883.png)

**Comment by kooritea** [comment]
偶然发现electron支持chrome的命令行开关，顺势就用上了_(:_」∠)_
