### ISSUE TITLE
刷新二维码无法点击

### ISSUE THREAD

**Issue by amitbha** [kooritea/electronic-wechat#29]
#### Description

要求刷新二维码的时候无法点击刷新。
![default](https://user-images.githubusercontent.com/4060625/41905712-8785dea6-796e-11e8-8cc2-61efe41fd080.png)

#### Specifications

- Version: `v2.1.3`

**Comment by left3721** [comment]
我也遇到这个问题，点击不了。

**Comment by kooritea** [comment]
这个二维码好像会自动刷新。。
我等了好久都没有点击刷新
