### ISSUE TITLE
发起多人聊天 选择联系人界面 点插无法取消

### ISSUE THREAD

**Issue by shishliang** [kooritea/electronic-wechat#3]
#### Description

First of all, thanks for your attention to open an issue for this project.
Please notice that if you are requesting a **feature**, then you should give a **brief description** of your request.
If you are reporting a **bug**, please **follow the template** below.
A bug report **without detailed information** required will have a **very low priority** and even be **ignored** (closed directly)!

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by kooritea** [comment]
无法复现。。。
还是我理解得不对。可以发截图让我看看吗

**Comment by kooritea** [comment]
是运行发布了的2.0.5版吗？
我现在直接跑源码没有这个问题，可能是在解决地方无法点击问题的时候顺便把这里也弄好了。。
