### ISSUE TITLE
打开后出现 "A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by elonliu** [kooritea/electronic-wechat#31]
#### Description

每次打开应用后都会弹出如图报错窗口，关掉后才出现二维码。该报错目测不影响正常功能，但是很烦。

#### Specifications

- Version of Electron (run `$ electron --version`): Release version v2.1.4
- OS: Ubuntu 16.04
- Screenshot
![screenshot from 2018-07-06 19-55-08](https://user-images.githubusercontent.com/5549178/42377786-688ea8c0-8157-11e8-8811-1d446c8dc7b8.png)

**Comment by kooritea** [comment]
应该是自动更新返回值格式化出错了，临时可能的解决方法：在设置哪里关掉自动检查更新
