### ISSUE TITLE
登录界面二维码静置失效后，刷新按钮无法点击

### ISSUE THREAD

**Issue by Karmenzind** [kooritea/electronic-wechat#32]
如题
环境是  ArchLinux + i3wm
软件版本如下
![image](https://user-images.githubusercontent.com/17923071/42863288-2f3227e0-8a95-11e8-8ca3-8683999c5a16.png)

**Comment by kooritea** [comment]
之前已经有人说过这个问题。。。
主要是我一直等不到它二维码过期需要刷新

**Comment by Karmenzind** [comment]
为啥会等不到……放那儿不管一会儿就有了……

**Comment by kooritea** [comment]
我在本地看是会自动刷新的

**Comment by Karmenzind** [comment]
唔，，回去录个视频给你

**Comment by kooritea** [comment]
emm不用录视频也可以了
我是知道会有二维码会过期，主要是无法复现没办法处理，我再想想办法

**Comment by Karmenzind** [comment]
好，加油，支持
对了，原作者为啥不更新了，你跟他交流过没

**Comment by kooritea** [comment]
没有。
我找到那个项目的时候原作者已经弃坑了
当时因为原项目问题很多根本不能愉快使用所以有了这个fork，随便学习electron

**Comment by amitbha** [comment]
#29 
我是下次登录时直接点登录按钮，不用刷二维码。但用着用着就失效了
如果要重现的话，可以在登陆状态下把网络断掉一会，再连上试试
