### ISSUE TITLE
在ubuntu 18.04上，输入法候选词框定位不准

### ISSUE THREAD

**Issue by androrz** [kooritea/electronic-wechat#33]
#### Description

在ubuntu 18.04上，输入法候选词框定位不准，候选词框会飘到屏幕外面去，geek的版本貌似没这个问题
#### Specifications

版本2.1.5

```
no stack trace
```

**Comment by kooritea** [comment]
无法复现。。
我想这不是electron的问题

**Comment by xiayurain95** [comment]
貌似在高分屏上面更容易出现这个问题，据说貌似是chromium的问题

**Comment by kooritea** [comment]
突然暴露了我不是高分屏_(:_」∠)_
