### ISSUE TITLE
未读消息计数经常不显示

### ISSUE THREAD

**Issue by elonliu** [kooritea/electronic-wechat#36]
#### Description
关闭桌面通知后，正常情况有新消息进来会在程序图标上显示未读信息数目的小数字，在状态栏也会有小红点提示。但是这个经常失效。程序里接收到了新消息，但是图标上没有正常显示未读消息提示。

#### Specifications

- Version of Electron (run `$ electron --version`): `v2.1.5`
- OS: `Ubuntu 16.04`

**Comment by kooritea** [comment]
是微信被其他窗口阻挡的时候不显示小红点吗
如果是这样的话解决方法就是当不使用微信的时候将微信最小化或缩小到托盘，因为只有进入这两个状态微信才不会把新消息设置为已读
现在正在考虑的是要不要让微信在失去焦点的时候进入这个状态

**Comment by elonliu** [comment]
谢谢。验证了一下，确实是因为窗口没有最小化或关闭到托盘所致。
不过个人觉得失焦即未读的设定更为合理。

**Comment by kooritea** [comment]
2.1.6已经改为失焦挂起啦

**Comment by elonliu** [comment]
赞！
