### ISSUE TITLE
能否加入快捷键唤起

### ISSUE THREAD

**Issue by runmain** [kooritea/electronic-wechat#38]
如题，能否加入类似ctr+alt+Z 这样唤起聊天界面

**Comment by kooritea** [comment]
ctrl+alt+w

**Comment by amitbha** [comment]
> ctrl+alt+w

是否支持命令行选项唤起？这样方便自定义唤起快捷键

**Comment by kooritea** [comment]
在关闭允许多实例的情况下可以直接用命令行运行那个可执行文件唤起

允许多实例的情况下还不支持

**Comment by amitbha** [comment]
哦，对我来说，ctrl+alt+w 无法单手搞定
那我关闭多实例吧
