### ISSUE TITLE
聊天窗口状态不能保持?

### ISSUE THREAD

**Issue by oreak** [kooritea/electronic-wechat#39]
比如 当前窗口在群里聊天, 这时候 最小化 窗口, 然后 点击 状态栏图标唤出界面, 这时候 就没有在原来群窗口了, 而是没有选中任何聊天窗口. 这是不应该的, 应该保持 窗口状态.

**Comment by kooritea** [comment]
我昨天发现这个问题
晚上回去我就发新版

**Comment by sansroman** [comment]
然而还没有修复,哈哈哈  我晚上回去也跟跟看

**Comment by sansroman** [comment]
emmm  已经修复了...

**Comment by kooritea** [comment]
忘记关issues了- -
