### ISSUE TITLE
退出到状态栏

### ISSUE THREAD

**Issue by kulongwangzhi85** [kooritea/electronic-wechat#4]
#### Description

First of all, thanks for your attention to open an issue for this project.
Please notice that if you are requesting a **feature**, then you should give a **brief description** of your request.
If you are reporting a **bug**, please **follow the template** below.
A bug report **without detailed information** required will have a **very low priority** and even be **ignored** (closed directly)!

#### Specifications

- Version of Electron (run `$ electron --version`): `v2.0.6`
- OS: `Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic`
- Stack trace from the error message (if any)

```
能否实现退出到状态栏,感谢.
```

**Comment by kooritea** [comment]
下个版本会可供选择退出是退出程序或最小化缩小到状态栏

**Comment by vic-feng** [comment]
已经点了start跟watching，由于是在Ubuntu 18.04 LTS下办公与娱乐，一天至少8小时在使用electronic-wechat，很期待下个版本会可供选择退出是退出程序或最小化缩小到状态栏

**Comment by kooritea** [comment]
谢谢支持！><
已经支持缩小到托盘的[v2.0.7](https://github.com/kooritea/electronic-wechat/releases/tag/v2.0.7)已经发布啦

**Comment by kulongwangzhi85** [comment]
辛苦了

**Comment by kulongwangzhi85** [comment]
初始窗口能不能调整大些,或者有记忆功能.每次启动都得手工调整窗口大小.谢谢.

**Comment by kooritea** [comment]
这个应该可以实现，有时间我去看一下

**Comment by amitbha** [comment]
@kooritea 能否实现 ESC 关闭到托盘？因为频繁查看微信，寻找并点击关闭按钮比较痛苦

**Comment by kooritea** [comment]
@amitbha 下个版本可以实现
因为esc键会和有些输入法冲突，会在设置中选择是否开启此功能
