### ISSUE TITLE
Segfault with glibc 2.28

### ISSUE THREAD

**Issue by xinchi-he** [kooritea/electronic-wechat#41]
#### Description

Segfault with glibc 2.28 under archlinux, please include a glibc 2.27 inside the package like what slack and skypeforlinux did for the recent glibc mitigation strategy.

Thanks.

#### Specifications

- OS: `Arch Linux 4.17.11-1-ck-silvermont`
- Version: `v2.1.7`

```
[1]    6541 segmentation fault (core dumped)  electronic-wechat
```

**Comment by kooritea** [comment]
electron 2.0.8 已经修复这个问题
