### ISSUE TITLE
今天发现微信登陆不了

### ISSUE THREAD

**Issue by liangjiongyao** [kooritea/electronic-wechat#49]
今天早上开电脑之后发现electronic-wechat登陆不了，命令行返回reconnect
[root@localhost electronic-wechat-linux-x64]# ./electronic-wechat
Reconnect.
Reconnect.
Reconnect.
Reconnect.
......
只有我一个人出现这个情况吗？

**Comment by amitbha** [comment]
我这里正常，请给出环境

**Comment by kooritea** [comment]
网络不通，检查一下代理设置
