### ISSUE TITLE
不能使用搜狗输入法

### ISSUE THREAD

**Issue by xiongmaoshouzha** [kooritea/electronic-wechat#5]
不能使用搜狗输入法

**Comment by kulongwangzhi85** [comment]
我的可以,ubuntu18.04 搜狗版本:v2.2.0.0108

**Comment by kooritea** [comment]
是不是使用的root权限启动？

**Comment by xiongmaoshouzha** [comment]
@kooritea 我下的是zip包，开始没用sudo就一直卡在启动的界面，用的sudo后就秒开

**Comment by kooritea** [comment]
@xiongmaoshouzha 一直卡在启动界面可能是因为无法获取登录二维码导致的，你有设置系统代理吗

**Comment by xiongmaoshouzha** [comment]
@kooritea 我知道了，用了蓝灯，我去掉试试。多谢

**Comment by vic-feng** [comment]
@xiongmaoshouzha 
我可以使用搜狗拼音输入法正常输入文字

最近Ubuntu 18.04 LTS自带的ibus输入法出现了问题，无法通过空格或者序号正确的去选择文字，直接卸载了ibus，接着安装了fcitx
```bash
    sudo apt autoremove ibus ibus-gtk ibus-gtk3
    sudo apt purge ibus
    sudo apt install fcitx
```
最后安装了搜狗拼音输入法，同时通过Fcitx配置了输入法，增加了
    搜狗拼音、键盘-英语(美国)

**Comment by NoobHua** [comment]
我使用搜狗输入法，输入框无法显示出来，有没有人和我遇到一样的问题？
