### ISSUE TITLE
failed at the electronic-web@2.1.9 start script 'electron src/main.js'

### ISSUE THREAD

**Issue by guoyanzhang0817** [kooritea/electronic-wechat#50]
OS: ubuntu 18.04.1 LTS
step 1: git clone https://github.com/kooritea/electronic-wechat.git
step 2: npm install && npm start
......
failed at the electronic-web@2.1.9 start script 'electron src/main.js'
......

my e-mail: 1746902011@qq.com

**Comment by kooritea** [comment]
step 1: rm -rf ./node_modules
step 2: 'npm install' or 'cnpm install'    don't use &&
step 3: npm start
