### ISSUE TITLE
关闭微信之后有electron进程驻留

### ISSUE THREAD

**Issue by roachsinai** [kooritea/electronic-wechat#51]
#### Description

使用wechat之前没有打开electron相关进程，但是使用wechat并关闭之后，还有相关相关进程。

#### Specifications

- Version of Electron: `v2.0.8`
- OS: `Manjaro Gnome`

**Comment by kooritea** [comment]
ctrl + alt + w 能唤出微信吗？
如果可以：则微信只是缩小到托盘菜单并没有退出程序(设置中有相关设置)(可能你看不见托盘菜单的微信图标 electron解决方法是安装libappindicator1，或者参考 #8 )
如果不可以：希望提供残留进程的详细信息

**Comment by kooritea** [comment]
这个不清楚   因为我也是使用gnome但是我并没有设置Exec=env XDG_CURRENT_DESKTOP=Unity  也能正常使用托盘图标。。。

**Comment by roachsinai** [comment]
好的，感谢！
