### ISSUE TITLE
下载图片后突然返回No chats selected页面

### ISSUE THREAD

**Issue by JachinShen** [kooritea/electronic-wechat#52]
#### Description

下载图片后会突然返回到No chats selected页面，而不是留在下载图片的chat页面，即使取消下载也会返回。

#### Specifications

- Version of Electron (run `$ electron --version`): `v2.0.8`
- OS: `Manjaro 17.1.12`
- Stack trace from the error message (if any)

```
Gtk-Message: 23:24:32.573: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by kooritea** [comment]
在设置中把失焦处理关闭即可
