### ISSUE TITLE
请问这个项目可以做微信的消息拦截开发吗

### ISSUE THREAD

**Issue by yq5858588** [kooritea/electronic-wechat#53]
#### Description
请问这个项目可以做微信的消息拦截开发吗？就是说可以拦截到发送出去或者接受的消息，并对接收人和发送人的消息进行分类统计，不知道这个项目可以实现吗

**Comment by kooritea** [comment]
现阶段所有消息都保存在了以uin命名的IndexedDB里面，有需要的话自行导出就好了
并且不打算做这方面的开发
