### ISSUE TITLE
Feature request (or maybe a bug?): 掉线一键登录，无须重新扫码

### ISSUE THREAD

**Issue by bryango** [kooritea/electronic-wechat#55]
#### Description
之前在使用 [geeeeeeeeek](https://github.com/geeeeeeeeek/electronic-wechat) 的旧版以及 [官方网页版](https://wx.qq.com) 时，掉线后（如电脑休眠唤醒后）重连微信，往往可以一键登录，无须重新扫码，界面如下：
![wechat-login](https://user-images.githubusercontent.com/26322692/45913674-9aa2bc80-be69-11e8-9f4f-d363d9688eae.png)
然而，用此分支版本时，发现几乎不出现这个一键登录的界面，而是基本上每次都得重新扫码... 会不会跟 cookie 有关？（瞎猜...）

#### Note
已有一段时间未使用 geeeeeeeeek 旧版，不保证这一特性至今尚存。

#### P. S.
建议可以开通一个捐赠渠道，大佬辛苦啦！@kooritea 

#### Specifications
- Version of Electron (run `$ electron --version`): `v2.0.8`
- OS: `Linux 4.14.70-1-MANJARO x86_64`

**Comment by kooritea** [comment]
应该是时间不够长
具体判定条件不是很清楚
最开始使用的时候我也是每次都要扫二维码
相当一段时间之后现在才可以使用一键登录
