### ISSUE TITLE
下载文件后聊天窗口丢失

### ISSUE THREAD

**Issue by amitbha** [kooritea/electronic-wechat#56]
#### Description

在某个聊天窗口内下载文件，下载完后，界面自动回到无任何聊天窗口的状态。很不方便

#### Specifications

- Version of Electron: `v2.2.0`
- OS: `linux`

**Comment by kooritea** [comment]
在设置中关闭失焦处理

**Comment by amitbha** [comment]
哦，原来是没理解挂起的意思
