### ISSUE TITLE
消息通知能否设置成选项，隐藏或显示？

### ISSUE THREAD

**Issue by robinjackson** [kooritea/electronic-wechat#57]
有的时候屏幕要共享给别人，能否在偏好配置中加一个选项，“在消息通知中隐藏详细内容”？

**Comment by kooritea** [comment]
这个关系到拦截原生notification
鉴于之前拦截notification导致缺消息的问题，需要仔细研究一下

**Comment by kooritea** [comment]
仔细想了下 用微信自带的 ‘关闭桌面通知’ 就好了呀

**Comment by mengyaoss77** [comment]
这个feature好像已经有了, 还希望更精准一些. 就是只显示"收到一条微信消息"字样, 不显示是谁发来的更好了.
