### ISSUE TITLE
扫码后没有登入

### ISSUE THREAD

**Issue by royceniu** [kooritea/electronic-wechat#59]
#### Description

每次在扫码后，之出现一个白条，没有其他反应

我测试了从AUR下载或者直接从Github Release最新版，都一样不行。

白色的条如图：https://pasteboard.co/HH1srsZ.png （扫码成功后出现）

#### Specifications

- Version of Electron (run `$ electron --version`): `v2.0.9`
- OS: `Antergos (Archlinux)`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by royceniu** [comment]
Hi, 
Ctrl+Shfit+I 和 F12我都试了，没反应

**Comment by kooritea** [comment]
打开微信
先ctrl+shift+i
然后看一下坐上角把开发者工具设置成独立窗口
再扫码

**Comment by royceniu** [comment]
Hi, 不知道为什么，按照你说的把开发者工具设置成独立窗口之后，什么都没改自己就好了，打扰了
