### ISSUE TITLE
有时无法关闭

### ISSUE THREAD

**Issue by kulongwangzhi85** [kooritea/electronic-wechat#6]
#### Description

First of all, thanks for your attention to open an issue for this project.
Please notice that if you are requesting a **feature**, then you should give a **brief description** of your request.
If you are reporting a **bug**, please **follow the template** below.
A bug report **without detailed information** required will have a **very low priority** and even be **ignored** (closed directly)!

#### Specifications

- Version of Electron (run `$ electron --version`): 
- OS: `ubuntu18.04`
- Stack trace from the error message (if any)

```
有时单击关闭按钮，无法关闭。需要使用下ctrl+alt+w，再按就可以退出到状态栏
```

**Comment by kooritea** [comment]
这个希望你可以详细观察一下触发这个问题的条件，我也预想过这个问题但是一直找不到怎么触发

**Comment by kulongwangzhi85** [comment]
牛逼！

**Comment by vic-feng** [comment]
这种问题可能是偶现的，我也在使用Ubuntu 18.04并且昨天刚更新了内核到4.15.0-22-generic，目前木有出现这个issue描述的问题
