### ISSUE TITLE
启动报 “段错误 (核心已转储)”

### ISSUE THREAD

**Issue by chestnut-egg** [kooritea/electronic-wechat#62]
./electronic-wechat
段错误 (核心已转储)

系统为：
Linux version 4.18.0-7-generic (buildd@lgw01-amd64-029) (gcc version 8.2.0 (Ubuntu 8.2.0-4ubuntu1)) #8-Ubuntu SMP Tue Aug 28 18:24:42 UTC 2018

**Comment by kooritea** [comment]
https://github.com/electron/electron/issues/13972
