### ISSUE TITLE
能否支持缩放

### ISSUE THREAD

**Issue by mengyaoss77** [kooritea/electronic-wechat#64]
ubuntu 18.04 
1920x1080 14英寸 显示太小了

**Comment by kooritea** [comment]
把鼠标移动到左下角或右下角就可以缩放呀？

**Comment by mengyaoss77** [comment]
> 把鼠标移动到左下角或右下角就可以缩放呀？

不是的，我是指类似Chrome中按住Ctrl 滚动滚轮的那种形式的缩放。

**Comment by kooritea** [comment]
emm这个确实不支持

**Comment by mengyaoss77** [comment]
[electronic-wechat高分屏下的缩放修改](https://blog.csdn.net/u013401853/article/details/68951577)
我搜到了篇博客，不知道这个能不能做到动态调整

**Comment by kooritea** [comment]
可以试试
