### ISSUE TITLE
微信表情商店的表情包不支持

### ISSUE THREAD

**Issue by HarryHq** [kooritea/electronic-wechat#65]
#### 在微信表情商店下载的表情显示不正常

* 在桌面上的表情显示
![image](https://user-images.githubusercontent.com/33572465/48039199-b6121e80-e1ae-11e8-8feb-68e93728f78d.png)

* 在手机上的表情显示
![image](https://user-images.githubusercontent.com/33572465/48039263-f83b6000-e1ae-11e8-97dd-71c8f7a5caa0.png)

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
![image](https://user-images.githubusercontent.com/33572465/48039304-2c168580-e1af-11e8-9424-6293060e6877.png)

- OS: `<Ubuntu 18.04>`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by kooritea** [comment]
这个没有办法
微信的接口没有返回商店的表情
