### ISSUE TITLE
历史聊天记录的存储位置以及删除方式

### ISSUE THREAD

**Issue by questioner0** [kooritea/electronic-wechat#69]
#### Description

非常感谢你对原来那个项目的持续改进和更新！使用体验非常不错！

因为是在非私人的电脑上使用，所以我想知道这个软件的聊天记录是存储在什么地方、以及如何删除。

我使用的是release版本(V2.2.0)，解压后直接运行。但是如果把整个文件夹删除，重新下载运行，历史聊天记录还是存在的。所以很好奇如果我想要删除历史聊天记录，应该怎么操作？ （另外我并没有前端相关的知识，如果有详细步骤就更好了！）

谢谢！

#### Specifications

- OS: `Ubuntu 18.04`

**Comment by slimtom95** [comment]
个别时候登录不上，一直显示Reconnect时，楼上此法亦能解决此问题
