### ISSUE TITLE
通过创建的WeChat.desktop来启动程序，状态栏会出现多个electronic-wechat

### ISSUE THREAD

**Issue by vic-feng** [kooritea/electronic-wechat#7]
#### Description
WeChat.desktop内容如下
```bash
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon[zh_CN]=/home/$USER/.local/electronic-wechat-linux-x64/246x0w.jpg
Name[zh_CN]=WeChat
Exec=/home/$USER/.local/electronic-wechat-linux-x64/electronic-wechat
Categories=Network;
```
直接通过收藏夹来启动程序的时候发现了这个问题，如果WeChat.desktop在桌面，也会出现同样的问题

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `Ubuntu 18.04 LTS`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by kooritea** [comment]
这是我放在/usr/share/applications下的electronic-wechat.desktop
```bash
[Desktop Entry]
Name=Electronic Wechat
Comment=Unofficial WeChat client built with React, MobX and Electron.
Exec=/opt/wechat/electronic-wechat %U
Terminal=false
Type=Application
Icon=/home/koori/图片/icon/wechat.png
#Icon=/opt/wechat/electronic-wechat
Categories=Chat;
```
暂时没有出现多个electronic-wechat的问题

自从17.10换了gnome之后desktop的配置就有点迷了。。
以前我也遇到过你这样的启动程序之后会额外出现一个icon的问题，不知怎样就解决了

**Comment by vic-feng** [comment]
我试过了将desktop文件放在了/usr/share/applications下，还是有同样的问题，不知道由于什么原因造成的

**Comment by vic-feng** [comment]
先关闭掉这个issue，这种问题能帮助到https://github.com/kooritea/electronic-wechat/issues/12
