### ISSUE TITLE
gnome 3 启动，图标任务栏不会与收藏的icon合并。

### ISSUE THREAD

**Issue by izern** [kooritea/electronic-wechat#87]
#### Description
gnome 3 启动，图标任务栏不会与收藏的icon合并。
![image](https://user-images.githubusercontent.com/17672970/52109422-5d7ce100-2638-11e9-8a14-7fa250552bc1.png)
/usr/share/applications/wechat.desktop 添加到收藏夹，然后单机图标打开会新生成一个图标在任务栏
```
[Desktop Entry]
Comment=wechat 
Terminal=false
Name=wechat
Exec=/opt/wechat-linux-x64/electronic-wechat
Type=Application
Icon=/opt/wechat-linux-x64/assets/icon.png

```

#### Specifications

- Version of Electron (run `$ electron --version`): `2.3.0`
- OS: `Linux debian 8`
- Stack trace from the error message (if any)

**Comment by kooritea** [comment]
gnome貌似是根据name值来决定是否合并图标的，建议把desktop的name改为`Electronic Wechat`再试一下
如果还不行再加一项
```
StartupWMClass=Electronic Wechat
```

**Comment by izern** [comment]
Name=electronic-wechat
StartupWMClass=electronic-wechat
生效了。
但是点击X退出到系统托盘功能有些BUG仍然会直接退出。跟旁边的↓点击效果不一致。
