### ISSUE TITLE
在终端直接执行./electronic-wechat 一直报reconnect

### ISSUE THREAD

**Issue by changewupeng** [kooritea/electronic-wechat#88]
为什么在终端直接执行./electronic-wechat 一直报reconnect
![image](https://user-images.githubusercontent.com/34981119/52927242-801b3380-3374-11e9-8dd4-636091894dbe.png)

而直接用鼠标点击可以打开

**Comment by kooritea** [comment]
用 env 看看是不是设置了无效http代理
如果是，在设置里面选择直接连接就好了

**Comment by changewupeng** [comment]
后面下载了最新的版本，没出现此问题
