### ISSUE TITLE
有边框窗口后设置按钮消失的问题

### ISSUE THREAD

**Issue by Starishli** [kooritea/electronic-wechat#91]
从无边框窗口设置成有边框窗口后，发现原来“设置”按钮找不到了:<

**Comment by kooritea** [comment]
有边框只能从托盘图标打开设置页了

**Comment by Starishli** [comment]
诶，那看来可能是我这个系统的问题。我这个是fedora29，托盘图标里也找不到。不过还是谢谢啦～比网页版好用很多了

**Comment by kooritea** [comment]
没有托盘图标可以参考这个 #8

**Comment by Starishli** [comment]
在gnome-extension上面装了个托盘图标的支持，可以正常用啦
