### ISSUE TITLE
"阅读“bug（低影响）

### ISSUE THREAD

**Issue by ray-github-hybrid** [kooritea/electronic-wechat#92]
#### Description

在“阅读”内打开公众号文章阅读，在Console中可见Error和Warning。

#### Specifications

- Version of Electron 2.3.1
- OS: Linux 4.20.8-100.fc28.x86_64

**Comment by ray-github-hybrid** [comment]
不新开issue了，还有两点建议：
1. 托盘中微信图标鼠标左右点击功能一样，建议改成左击呼出/拉起主窗口（即右点击中的show）
2. 首次点开peference, Setings窗口貌似默认“Always on Top"

**Comment by kooritea** [comment]
阅读里面的console error warming全都是原版微信的代码，这里改不了

托盘图标左右键一样是因为electron在使用`应用程序指标`时会忽略点击事件（不可控
在electron的项目中这个问题在大吵特吵 4.0.0还没解决

偏好设置设定上是置顶的 毕竟偏好设置的页面在不使用的时候关掉就可以了没必要保留占用内存

**Comment by ray-github-hybrid** [comment]
非常好的解释，我来关了这个issue。希望有更多人加入开发，尤其是UI美化方面 :)
